### ISSUE TITLE
Stamen Terrain Basemap

### ISSUE THREAD

**Issue by ralfWessels** [qgiscloud/qgis-cloud-plugin#59]
Hi,
when I add the "Stamen Terrain / OSM" basemap from QGIS Cloud Plugin it's ok in QGIS Desktop (version 3.26.3) but in the QGIS Web Client it just shows part of Northern America (see screenshot).
If I take the same basemap from QuickMapServices-Plugin it also shows up in the QGIS Web Client ...but then I can't switch basemaps with the basemap switch function. 
Best greetings from Berlin
Ralf Wessels

![image](https://user-images.githubusercontent.com/52887287/191050907-2c490f3c-1473-43be-9169-826a30fd54bc.png)

**Comment by tpo** [comment]
Hi @ralfWessels ,

woah the Dead Kennedys logo as avatar, nice!!! ("Holiday in Cambodia" is still one my top favored punk songs). Back to topic: would you mind opening a ticket at http://support.qgiscloud.com ? You can also refer to this ticket from the qgiscloud support ticket.

Thanks and greets, Punks not dead,
*t

**Comment by tpo** [comment]
Assuming that this problem got resolved via http://support.qgiscloud.com I am closing this ticket. Please reopen with a note what the current problems are in case my assumption was wrong.

**Comment by ralfWessels** [comment]
Hi Thomas,
QGIS Cloud Support can reproduce the problem ...and i hope they are working on a solution  ("_I can reproduce this problem, forwarding the ticket to our expert._") 
...so far the problem still exists...
